backend:
  name: github
  repo: jdp4v/aces-technology-next
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: test
    label: Test
    folder: src/content/test
    create: false
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
